version: '3'

services:

  voucherapi:
    build:
      context: ./../voucherapi
      dockerfile: ./../voucherapi/voucherapi.dockerfile
    restart: always
    ports:
      - "3000:80"
    deploy:
      mode: replicated
      replicas: 1